### ISSUE TITLE
Light blue circle is ruining my day

### ISSUE THREAD

**Issue by SexyStallman** [Noremos/Drakengard3-helper#1]
The circles for button press timing come in various colors, but the light blue one is really hard to see against the white background. This makes timing button presses for the light blue circles difficult. Please consider changing the light blue to another circle, or using a consistent, easy to view color such as red rather than alternating colors.

**Comment by Noremos** [comment]
Thank you for your activity, I am very glad that my project was useful to someone. I removed the light blue color and increased the width of the circle lines. I hope this helps you.
The new version is available at: https://github.com/UnknownAr/Drakengard3-helper/releases/tag/v.1.2

**Comment by SexyStallman** [comment]
Works a lot better, visibility is greatly improved. Timings feel a little tighter due to the wider circles, but are well within acceptable limits.  Watching the end credits right now. :)
