### ISSUE TITLE
THANK YOU!!!

### ISSUE THREAD

**Issue by ShironCat** [Noremos/Drakengard3-helper#2]
I couldn't find any other way to contact you, that's why I'm writing an issue. I just wanted to thank you for helping me finish Drakengard 3. Know that the work you did is well appreciated. 👍✨🌟

**Comment by Noremos** [comment]
> I couldn't find any other way to contact you, that's why I'm writing an issue. I just wanted to thank you for helping me finish Drakengard 3. Know that the work you did is well appreciated. 👍✨🌟

Glad to help you!
